/**
 * SPEC-ARCH-CRAWLER-001 Phase 3 (REQ-CRAWLER-006) — new-platform scaffold.
 *
 * WHY THIS EXISTS
 * ---------------
 * REQ-CRAWLER-004 already collapsed "add platform #33" from "copy-paste a
 * whole module" down to "supply a Parser strategy + a selector-registry
 * entry + one register() line". REQ-CRAWLER-006 removes the remaining
 * boilerplate: this tool GENERATES that skeleton (a Parser strategy stub,
 * a DETAIL_REGISTRY entry stub, and the exact register() wiring snippet)
 * so a developer fills in selectors instead of hand-typing structure.
 *
 * [HARD] SCAFFOLD ONLY — this tool is intentionally inert against the live
 * codebase:
 *   - It NEVER mutates an existing source file (no edits to
 *     parser-strategy.ts / selector-registry.ts / detail/index.ts).
 *   - It NEVER implements a real site (REQ-006 explicitly excludes the
 *     actual site #33 implementation — only the skeleton is produced).
 *   - Default mode is dry-run: it prints the three snippets to stdout and
 *     writes nothing. `--write` opt-in writes ONE new, clearly-namespaced
 *     stub file (src/lib/parsers/scaffold/<key>-platform.scaffold.ts) and
 *     refuses to overwrite if that file already exists.
 *
 * Run via:  npm run scaffold:platform -- <key> [--name "Display Name"] [--write]
 *      or:  tsx tools/scaffold-platform.ts <key> [--name "Display Name"] [--write]
 *
 * @MX:SPEC: SPEC-ARCH-CRAWLER-001 REQ-CRAWLER-006
 */

import * as fs from "node:fs"
import * as path from "node:path"
import {fileURLToPath} from "node:url"

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = path.resolve(__dirname, "..")

export interface CliArgs {
  key: string
  displayName: string
  write: boolean
}

/** A platform key must be a safe lowercase identifier (used in a filename
 *  + as a TS class-name stem + as a registry map key). Reject anything
 *  that would not round-trip cleanly so a typo never produces broken code. */
export const KEY_RE = /^[a-z][a-z0-9-]{1,40}$/

export class ScaffoldError extends Error {}

export function parseArgs(argv: string[]): CliArgs {
  const positional: string[] = []
  let displayName = ""
  let write = false

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === "--write") {
      write = true
    } else if (arg === "--name") {
      const next = argv[i + 1]
      if (next === undefined) {
        throw new ScaffoldError('--name requires a value, e.g. --name "Acme Store"')
      }
      displayName = next
      i++
    } else if (arg.startsWith("--name=")) {
      displayName = arg.slice("--name=".length)
    } else if (arg.startsWith("--")) {
      throw new ScaffoldError(`Unknown flag: ${arg}`)
    } else {
      positional.push(arg)
    }
  }

  const key = positional[0]
  if (!key) {
    throw new ScaffoldError(
      'Usage: tsx tools/scaffold-platform.ts <key> [--name "Display Name"] [--write]',
    )
  }
  if (!KEY_RE.test(key)) {
    throw new ScaffoldError(
      `Invalid platform key "${key}". Expected lowercase letters/digits/'-' ` +
        `starting with a letter (matches the existing DETAIL_REGISTRY keys, ` +
        `e.g. "blankroom"; a digit-leading site like "8division" needs a ` +
        `letter-leading key such as "eightdivision").`,
    )
  }
  return {key, displayName: displayName || key, write}
}

/** lower-kebab/`-`/digits key -> UpperCamel class stem. */
export function toClassStem(key: string): string {
  return key
    .split("-")
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("")
}

/** The Parser-strategy + registry-entry stub file body. This mirrors the
 *  exact shapes of the Phase 2/3 sources (parser-strategy.ts:Parser /
 *  selector-registry.ts:RegistryEntry / detail/types.ts:DetailData) so the
 *  generated file typechecks as soon as it is created. */
export function strategyStub(key: string, displayName: string): string {
  const Stem = toClassStem(key)
  return `/**
 * SPEC-ARCH-CRAWLER-001 REQ-CRAWLER-006 — SCAFFOLD STUB for platform
 * "${displayName}" (key: "${key}"). Generated by tools/scaffold-platform.ts.
 *
 * THIS IS A SKELETON, NOT A WORKING PARSER. Fill in the TODO markers, then
 * follow docs/add-platform.md to wire it in (selector-registry entry +
 * defaultParserRegistry.register). Until then this file is unreferenced by
 * the live crawl path and changes no behavior.
 */

import type {Page} from "playwright"

import type {Parser} from "../parser-strategy"
import type {DetailData} from "../detail/types"
import type {RegistryEntry} from "../detail/selector-registry"

/**
 * Input payload for the ${displayName} parse seam. Keep this minimal and
 * specific to what ${key} actually needs (mirror the per-platform input
 * shapes in parser-strategy.ts, e.g. Cafe24DetailInput).
 */
export interface ${Stem}ParseInput {
  site: string
  page: Page
  productUrl: string
}

/**
 * ${displayName} parser strategy. For a Cafe24-family site prefer routing
 * THROUGH the Phase 2 registry-driven path (see Cafe24DetailParserStrategy
 * in parser-strategy.ts) instead of re-implementing extraction here.
 *
 * TODO(${key}): implement parse() or delegate to the shared
 *   field-extractors / RegistryDetailParser path.
 */
export class ${Stem}ParserStrategy
  implements Parser<${Stem}ParseInput, Promise<DetailData>>
{
  readonly platform = "${key}"

  async parse(_input: ${Stem}ParseInput): Promise<DetailData> {
    // TODO(${key}): replace this stub. An un-finished scaffold must be
    // inert (throw) rather than silently emit wrong data.
    throw new Error(
      "${Stem}ParserStrategy is a scaffold stub — implement parse() per docs/add-platform.md",
    )
  }
}

/**
 * DETAIL_REGISTRY entry stub for "${key}". Copy this into
 * src/lib/parsers/detail/selector-registry.ts (DETAIL_REGISTRY map) and
 * fill the selectors. Only use \\\`strategy: "base"\\\` if ${key} genuinely
 * matches the BaseDetailParser family; otherwise add a new StrategyId +
 * strategy body in field-extractors/strategies.ts (see docs/add-platform.md).
 */
export const ${Stem.toUpperCase()}_REGISTRY_ENTRY: RegistryEntry = {
  strategy: "base", // TODO(${key}): confirm or introduce a new StrategyId
  wait: {kind: "dom", timeout: 15000, pauseMs: 800},
  descriptionSelectors: [
    // TODO(${key}): site-specific description container selectors
  ],
}
`
}

/** The copy-paste-ready snippets the developer pastes into the live files.
 *  Printed in BOTH dry-run and --write mode (the tool never edits those
 *  files itself — that paste step is the explicit human gate). */
export function wiringSnippets(key: string, displayName: string): string {
  const Stem = toClassStem(key)
  const scaffoldImport = `../scaffold/${key}-platform.scaffold`
  return `
============================================================================
 NEXT STEPS — paste these into the live files (the tool does NOT edit them)
============================================================================

1) src/lib/parsers/detail/selector-registry.ts
   Add to the DETAIL_REGISTRY object literal (alongside the 18 entries):

  ${key}: {
    strategy: "base", // TODO(${key}): confirm strategy / add a StrategyId
    wait: {kind: "dom", timeout: 15000, pauseMs: 800},
    descriptionSelectors: [/* TODO(${key}) selectors */],
  },

   (If a brand-new extraction algorithm is required, also add "${key}" to
    the StrategyId union and a strategy body in
    src/lib/parsers/field-extractors/strategies.ts.)

2) src/lib/parsers/detail/index.ts
   If "${key}" is a Cafe24-family detail site, add a registry-backed shim
   + DETAIL_PARSERS entry next to the existing 18 (no custom module):

  export class ${Stem}DetailParser extends RegistryDetailParser {
    constructor() {
      super("${key}")
    }
  }
  // ...and inside DETAIL_PARSERS:
  ${key}: () => new ${Stem}DetailParser(),

3) src/lib/parsers/parser-strategy.ts  (only if "${key}" needs a custom
   strategy beyond the declarative registry — REQ-CRAWLER-004 extension):

  import {${Stem}ParserStrategy} from "${scaffoldImport}"
  // ...append to the defaultParserRegistry chain:
  .register("${key}", () => new ${Stem}ParserStrategy())

4) tests/  — add a characterization test for "${key}" BEFORE finishing the
   implementation (fixture HTML/JSON -> parse result golden), mirroring
   tests/detail-parsers.characterization.test.ts. See docs/add-platform.md.

Platform: ${displayName} (key "${key}")
============================================================================
`
}

export function main(): void {
  let args: CliArgs
  try {
    args = parseArgs(process.argv.slice(2))
  } catch (err) {
    if (err instanceof ScaffoldError) {
      console.error(`scaffold-platform: ${err.message}`)
      process.exitCode = 1
      return
    }
    throw err
  }

  const {key, displayName, write} = args
  const stub = strategyStub(key, displayName)
  const snippets = wiringSnippets(key, displayName)

  const scaffoldDir = path.join(REPO_ROOT, "src", "lib", "parsers", "scaffold")
  const stubPath = path.join(scaffoldDir, `${key}-platform.scaffold.ts`)
  const relStubPath = path.relative(REPO_ROOT, stubPath)

  if (!write) {
    console.log(
      `# DRY RUN (no files written). Re-run with --write to create ${relStubPath}\n`,
    )
    console.log(`----- ${relStubPath} -----`)
    console.log(stub)
    console.log(snippets)
    return
  }

  if (fs.existsSync(stubPath)) {
    console.error(
      `scaffold-platform: refusing to overwrite existing ${relStubPath}. ` +
        `Delete it first or pick a different key.`,
    )
    process.exitCode = 1
    return
  }

  fs.mkdirSync(scaffoldDir, {recursive: true})
  fs.writeFileSync(stubPath, stub, "utf-8")
  console.log(`scaffold-platform: wrote ${relStubPath}`)
  console.log(snippets)
}

// Run main() only when invoked as a script (tsx tools/scaffold-platform.ts
// / npm run scaffold:platform). Importing this module (the smoke test does)
// must NOT trigger generation — keeps the test in-process and instant.
const invokedPath = process.argv[1]
  ? path.resolve(process.argv[1])
  : ""
if (invokedPath === fileURLToPath(import.meta.url)) {
  main()
}
