#!/usr/bin/env npx tsx
/** Verified official homepages found while re-auditing no-product brand nodes. */
import {createClient} from "@supabase/supabase-js"

const VERIFIED = [
  {
    id: 1649,
    brandName: "LCDC",
    homepageUrl: "https://shoplcdc.com",
    sources: ["https://en.shoplcdc.com/lcdc/about.html", "https://shoplcdc.com", "https://fashionseoul.com/224388"],
    storefront: "KR",
    currency: "KRW",
    note: "Official SHOP LCDC Korean store; exact LCDC fashion/lifestyle label and select-shop identity, Seoul operator details, direct e-shop, and KRW storefront verified.",
  },
  {
    id: 409,
    brandName: "ANCELLM",
    homepageUrl: "https://ancellm.com",
    sources: ["https://ancellm.com", "https://ancellm.com/pages/about", "https://rakutenfashionweektokyo.com/en/brands/detail/ancellm/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official ANCELLM Japanese store; exact label concept, Kazuya Yamachika identity, collections, stockists, and direct JPY catalogue verified.",
  },
  {
    id: 420,
    brandName: "PHILEO",
    homepageUrl: "https://phileo.paris",
    sources: ["https://phileo.paris", "https://phileo.paris/collections", "https://www.fhcm.paris/en/house/phileo"],
    storefront: "FR",
    currency: "EUR",
    note: "Official PHILEO Paris store; exact founder Philéo Landowski, Paris address, architectural-footwear identity, and direct EUR catalogue verified.",
  },
  {
    id: 610,
    brandName: "TONYWACK",
    homepageUrl: "https://tonywack.com",
    sources: ["https://tonywack.com", "https://en.tonywack.com/shopinfo/guide.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official TONYWACK Korean store; exact Seoul label identity, Korean shipping/support, direct catalogue, and KRW pricing verified.",
  },
  {
    id: 834,
    brandName: "SCULPTOR",
    homepageUrl: "https://sculptorpage.com",
    sources: ["https://sculptorpage.com", "https://sculptor-worldwide.com", "https://kream.co.kr/brand-stores/Sculptor/"],
    storefront: "KR",
    currency: "KRW",
    note: "Official SCULPTOR Korean store; exact Seoul label identity, domestic brand domain, direct KRW catalogue, and official worldwide store corroborated.",
  },
  {
    id: 841,
    brandName: "J KOO",
    homepageUrl: "https://studiojkoo.com",
    sources: ["https://en.studiojkoo.com/shopinfo/company.html", "https://studiojkoo.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official J KOO Korean store; exact designers Jinwoo Choi and Yeonjoo Koo, brand-name origin, matching official social identity, and direct catalogue verified.",
  },
  {
    id: 1465,
    brandName: "AFB",
    homepageUrl: "https://afb-afb-afb.com",
    sources: ["https://afb-afb-afb.com", "https://afb-afb-afb.com/pages/stockist"],
    storefront: "JP",
    currency: "JPY",
    note: "Official AFB Japanese online store; exact Japanese streetwear identity, matching @afb_official social handle, stockists, and JPY catalogue verified.",
  },
  {
    id: 53,
    brandName: "PDF",
    homepageUrl: "https://pdfchannel.com",
    sources: ["https://pdfchannel.com", "https://pdfchannel.com/pages/about-us"],
    storefront: "IT",
    currency: "EUR",
    note: "Official PDF (Project Domenico Formichetti) store; exact PDF CHANNEL identity, founder, direct apparel catalogue, and matching @pdf__channel social handle verified.",
  },
  {
    id: 56,
    brandName: "Dotthz",
    homepageUrl: "https://dotthz.com",
    sources: ["https://dotthz.com/en-us", "https://dotthz.com/en-us/pages/about"],
    storefront: "NL",
    currency: "EUR",
    note: "Official DOTTHZ store; exact Dutch label identity, Dotthz B.V. company information, direct bag catalogue, and matching social identity verified.",
  },
  {
    id: 4955,
    brandName: "HYKE",
    homepageUrl: "https://hyke.jp",
    sources: ["https://hyke.jp", "https://rakutenfashionweektokyo.com/jp/brands/detail/hyke/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official HYKE Japanese online store; exact label identity, designers, official-store linkage, collections, and JPY catalogue verified.",
  },
  {
    id: 4961,
    brandName: "SEVALI",
    homepageUrl: "https://www.sevalistudio.com",
    sources: ["https://www.sevalistudio.com", "https://www.fhcm.paris/en/house/sevali"],
    storefront: "FR",
    currency: "EUR",
    note: "Official SEVALI Studio site; exact Paris label, founder Sebastian A. de Ruffray, and official website link verified by FHCM.",
  },
  {
    id: 4977,
    brandName: "TH PRODUCTS",
    homepageUrl: "https://thproductsonline.com",
    sources: ["https://thproductsonline.com/en/pages/about", "https://thproductsonline.com/en/pages/store"],
    storefront: "JP",
    currency: "JPY",
    note: "Official th products Japanese store; exact label identity, designer Taro Horiuchi, Tokyo flagship, English/Japanese support, and catalogue verified.",
  },
  {
    id: 4990,
    brandName: "BOY'S OWN",
    homepageUrl: "https://www.boysownproductions.com",
    sources: ["https://www.boysownproductions.com/shop", "https://www.boysownproductions.com/products/juniorboysownwhite"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Boy's Own site and shop; exact British fanzine/club collective history and branded apparel catalogue verified.",
  },
  {
    id: 4999,
    brandName: "MACKINTOSH",
    homepageUrl: "https://www.mackintosh.com/en-kr",
    sources: ["https://www.mackintosh.com/en-kr/collections/womens", "https://www.mackintosh.com/en-kr/collections/womens-accessories"],
    storefront: "KR",
    currency: "KRW",
    note: "Official MACKINTOSH Korean-region store; en-kr locale, direct catalogue, Korean won prices, and regional shopping support verified.",
  },
  {
    id: 5004,
    brandName: "SCHOLL",
    homepageUrl: "https://www.scholl-shoes.com",
    sources: ["https://www.scholl-shoes.com/en-de", "https://www.yohjiyamamoto.co.jp/news/detail/ys-x-scholl-sabot-shoes/"],
    storefront: "EU",
    currency: "EUR",
    note: "Official Scholl fashion-footwear store; exact licensed brand identity, current catalogue, and Japanese fashion collaboration corroboration verified.",
  },
  {
    id: 5007,
    brandName: "QUARTERSNACKS",
    homepageUrl: "https://quartersnacksshop.com",
    sources: ["https://quartersnacksshop.com", "https://quartersnacksshop.com/pages/shipping-returns"],
    storefront: "US",
    currency: "USD",
    note: "Official Quartersnacks shop; exact label identity, direct apparel/skate catalogue, collaborations, and store policies verified.",
  },
  {
    id: 5008,
    brandName: "BY GLADHAND",
    homepageUrl: "https://shop.glad-hand.com/collections/by-gladhand",
    sources: ["https://shop.glad-hand.com/collections/by-gladhand", "https://shop.glad-hand.com/en"],
    storefront: "JP",
    currency: "JPY",
    note: "Official BY GLADHAND collection within the GLADHAND & Co. store; exact sub-label concept, English support, and JPY catalogue verified.",
  },
  {
    id: 5009,
    brandName: "GANGSTERVILLE",
    homepageUrl: "https://shop.glad-hand.com",
    sources: ["https://shop.glad-hand.com/en", "https://shop.glad-hand.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official GLADHAND & Co. group store carrying GANGSTERVILLE; exact GSV-labelled products, English support, and JPY direct catalogue verified.",
  },
  {
    id: 5010,
    brandName: "ATTRACTIONS",
    homepageUrl: "https://attractions.co.jp",
    sources: ["https://attractions.co.jp/pages/about-us", "https://attractions.co.jp/collections/all"],
    storefront: "JP",
    currency: "JPY",
    note: "Official ATTRACTIONS Japanese store; exact label story, Tokyo flagship, English brand information, and JPY catalogue verified.",
  },
  {
    id: 5012,
    brandName: "ROAR GUNS",
    homepageUrl: "https://roarguns.com",
    sources: ["https://roarguns.com/en/pages/about-us", "https://roarguns.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official roarguns Japanese online store; DB spacing/case variant matches the label history, designer, cross-gun identity, and direct catalogue.",
  },
  {
    id: 2556,
    brandName: "FAKE MAGAZINE",
    homepageUrl: "https://www.fakemagazine.kr",
    sources: ["https://www.fakemagazine.kr"],
    storefront: "KR",
    note: "Official Korean FAKE MAGAZINE site; exact publication identity and current fashion, culture, people, and work editorial catalogue verified.",
  },
  {
    id: 2558,
    brandName: "AIDOS MAGAZINE",
    homepageUrl: "https://aidosmagazine.com",
    sources: ["https://aidosmagazine.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official AIDOS MAGAZINE Korean store; exact publication identity, matching social channel, Seoul studio, company registration, and direct shop verified.",
  },
  {
    id: 2722,
    brandName: "FUNNI",
    homepageUrl: "https://funni.kr",
    sources: ["https://funni.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official FUNNI Korean store; exact object-brand identity, Seoul address, Korean business registration, and KRW catalogue verified.",
  },
  {
    id: 3800,
    brandName: "SUNMOONSTAR",
    homepageUrl: "https://sunmoonstar.kr",
    sources: ["https://sunmoonstar.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official SUNMOONSTAR Korean store; exact SMS label identity, Seoul operator registration, and KRW apparel catalogue verified.",
  },
  {
    id: 3807,
    brandName: "MUSED",
    homepageUrl: "https://musedofficial.com",
    sources: ["https://en.musedofficial.com", "https://musedofficial.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official MUSED Korean store; exact label philosophy, Seoul flagship, KR/global selector, and direct catalogue verified.",
  },
  {
    id: 3819,
    brandName: "FAF",
    homepageUrl: "https://fakeasflowers.com",
    sources: ["https://fakeasflowers.com", "https://rakutenfashionweektokyo.com/en/brands/detail/faf/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official FAF (Fake As Flowers) store; exact Tokyo label identity and official shop link corroborated by Rakuten Fashion Week Tokyo.",
  },
  {
    id: 3868,
    brandName: "FINCA",
    homepageUrl: "https://finca.kr",
    sources: ["https://finca.kr", "https://finca.kr/23"],
    storefront: "KR",
    currency: "KRW",
    note: "Official FINCA Korean store; exact designer-brand story, Seoul company registration, English/Korean support, and KRW catalogue verified.",
  },
  {
    id: 3873,
    brandName: "DIVE IN",
    homepageUrl: "https://divein.kr",
    sources: ["https://divein.kr/shopinfo/company.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official DIVE IN Korean apparel store; exact label identity, Seoul company registration, brand contact, and direct catalogue verified.",
  },
  {
    id: 3875,
    brandName: "AKKAM",
    homepageUrl: "https://aakam.kr",
    sources: ["https://aakam.kr/index.html", "https://www.musinsa.com/content/1402143626201536961"],
    storefront: "KR",
    currency: "KRW",
    note: "Official AAKAM Korean store; DB spelling AKKAM is a source typo, while the exact Korean label, products, flagship, and official retail identity match AAKAM.",
  },
  {
    id: 3880,
    brandName: "PICA",
    homepageUrl: "https://pica.xyz",
    sources: ["https://pica.xyz", "https://www.eqlstore.com/brands/main?brndCategoryNumber=BDMA0131B"],
    storefront: "KR",
    currency: "KRW",
    note: "Official PICA Korean fashion store; exact contemporary label identity, Seoul company registration, direct store, and EQL catalogue corroboration verified.",
  },
  {
    id: 3893,
    brandName: "NAATS",
    homepageUrl: "https://www.naats.co.kr",
    sources: ["https://www.naats.co.kr/product/list.html?cate_no=27&page=1", "https://kream.co.kr/brand-stores/Naats"],
    storefront: "KR",
    currency: "KRW",
    note: "Official NAATS Korean store; exact label identity, Seoul business registration, brand-domain contact, and direct catalogue verified.",
  },
  {
    id: 3894,
    brandName: "AMIMENT",
    homepageUrl: "https://amiment.co.kr",
    sources: ["https://amiment.co.kr", "https://www.29cm.co.kr/content/focus/2026/01/19/amiment"],
    storefront: "KR",
    currency: "KRW",
    note: "Official AMIMENT Korean store; exact label identity, Korean business registration, direct catalogue, and 29CM brand profile verified.",
  },
  {
    id: 3900,
    brandName: "S/E/O",
    homepageUrl: "https://s-e-o.co.kr",
    sources: ["https://en.s-e-o.co.kr", "https://collection.s-e-o.co.kr/en"],
    storefront: "KR",
    currency: "KRW",
    note: "Official s/e/o Korean store; exact stylized label, Seoul registration, KRW/USD selector, collections, and brand-domain contacts verified.",
  },
  {
    id: 3903,
    brandName: "SANIT JAMES",
    homepageUrl: "https://saint-james.co.kr",
    sources: ["https://saint-james.co.kr", "https://m.en.triplestore.co.kr/brands.html"],
    storefront: "KR",
    currency: "KRW",
    note: "DB and stockist spelling SANIT JAMES is a typo for SAINT JAMES; the official Korean store, heritage description, and KRW catalogue match the sourced label.",
  },
  {
    id: 3904,
    brandName: "SOONSU",
    homepageUrl: "https://soonsuofficial.com",
    sources: ["https://soonsuofficial.com", "https://www.nugu.jp/director/soonsu"],
    storefront: "KR",
    currency: "KRW",
    note: "Official SOONSU Korean fashion store; exact label identity, designer history, Seoul company registration, and direct KRW catalogue verified.",
  },
  {
    id: 3905,
    brandName: "NOREGRET",
    homepageUrl: "https://noregret.kr",
    sources: ["https://noregret.kr", "https://store.musinsa.com/app/brand_event/views/noregret/4619"],
    storefront: "KR",
    currency: "KRW",
    note: "Official NOREGRET Korean store; exact label identity, Korean company registration, KRW catalogue, and Musinsa brand profile verified.",
  },
  {
    id: 3906,
    brandName: "WELLBEING EXPRESS",
    homepageUrl: "https://wellbeingexpress.com",
    sources: ["https://wellbeingexpress.com", "https://wellbeingexpress.com/contact"],
    storefront: "KR",
    currency: "KRW",
    note: "Official WELLBEING EXPRESS Korean store; exact label identity, brand-domain customer support, direct shop, and Korean retail profiles verified.",
  },
  {
    id: 3909,
    brandName: "POINT OF TIME",
    homepageUrl: "https://pointoftime.co.kr",
    sources: ["https://pointoftime.co.kr/about", "https://seoul.designfestival.co.kr/exhibition/%ED%94%BC%EC%98%A4%ED%8B%B0/"],
    storefront: "KR",
    currency: "KRW",
    note: "Official POINT OF TIME (POT) Korean site; exact acronym and brand story, Seoul address, product range, and official design-festival profile verified.",
  },
  {
    id: 2236,
    brandName: "Luca Hamers",
    homepageUrl: "https://www.lucahamers.com",
    sources: ["https://www.lucahamers.com", "https://www.lucahamers.com/pages/privacy-policy"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Luca Hamers Heavy Industries store; exact designer identity, Luca Hamers Ltd legal details, contact domain, and technical-garment catalogue verified.",
  },
  {
    id: 2441,
    brandName: "MLGA",
    homepageUrl: "https://www.mlgastudio.com",
    sources: ["https://www.mlgastudio.com/pages/collection-02", "https://ciff.dk/news/mlga-interview"],
    storefront: "DK",
    currency: "DKK",
    note: "Official MLGA Studio site; Browns X MLGA collection and Copenhagen founder Marie-Louise Guldbæk Andersen corroborate the exact label.",
  },
  {
    id: 2460,
    brandName: "EVANGELI0N:95",
    homepageUrl: "https://www.evangelion95.jp",
    sources: ["https://www.evangelion95.jp/view/company", "https://www.evangelion95.jp"],
    storefront: "JP",
    currency: "JPY",
    note: "Official EVANGELION:95 Japanese online store; exact stylized brand, launch history, designer, and JPY catalogue verified.",
  },
  {
    id: 2461,
    brandName: "Fierce",
    homepageUrl: "https://fierce.kr",
    sources: ["https://fierce.kr/product/detail.html?cate_no=42&display_group=1&product_no=114", "https://fierce.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official FIERCE Korean store; exact Korean label identity, brand products, customer contact, and KRW catalogue verified.",
  },
  {
    id: 2469,
    brandName: "MASSES",
    homepageUrl: "https://masses-tokyo.com",
    sources: ["https://masses-tokyo.com", "https://www.massestokyo.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official MASSES Tokyo online store; exact label identity, official brand-site linkage, matching social identity, and JPY catalogue verified.",
  },
  {
    id: 2470,
    brandName: "EMOSTANCECLUB",
    homepageUrl: "https://www.emostanceclub-global.com",
    sources: ["https://www.emostanceclub-global.com/shop", "https://www.emostanceclub-global.com/commu"],
    storefront: "KR",
    currency: "USD",
    note: "Official EMOSTANCECLUB global store; exact label identity, Seoul return address, Korean operator terms, and direct catalogue verified.",
  },
  {
    id: 2479,
    brandName: "Darkr8m Studio",
    homepageUrl: "https://darkr8mstudio.bigcartel.com",
    sources: ["https://darkr8mstudio.bigcartel.com", "https://chanceclothing.co.kr/product/basic-logo-cap/6091/"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official DARKR8M STUDIO store; exact label products are corroborated by the Korean stockist's brand description and product catalogue.",
  },
  {
    id: 2503,
    brandName: "Opening Project",
    homepageUrl: "https://opening-project.com",
    sources: ["https://opening-project.com/category/about.html", "https://prtimes.jp/main/html/rd/p/000000446.000005203.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official OPENING PROJECT Korean site; exact brand concept, Seoul operator registration, stockists, and matching official social identity verified.",
  },
  {
    id: 2521,
    brandName: "XIYOBALL",
    homepageUrl: "https://www.xiyoball.com",
    sources: ["https://www.xiyoball.com/category/all/56/", "https://m.xiyoball.com/DH/about.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official XIYOBALL Korean store; exact label identity, Korean company registration, brand contact, and direct catalogue verified.",
  },
  {
    id: 2563,
    brandName: "Opening Project",
    homepageUrl: "https://opening-project.com",
    sources: ["https://opening-project.com/category/about.html", "https://prtimes.jp/main/html/rd/p/000000446.000005203.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Duplicate OPENING PROJECT node; official Korean site, Seoul operator registration, stockists, and matching official social identity verified.",
  },
  {
    id: 1485,
    brandName: "LUCAS BAUER",
    homepageUrl: "https://lucasbauerjewellery.com",
    sources: ["https://lucasbauerjewellery.com"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Lucas Bauer Jewellery store; exact designer name, jewellery collections, and matching official social identity verified.",
  },
  {
    id: 1507,
    brandName: "The K Label",
    homepageUrl: "https://www.theklabel.com",
    sources: ["https://www.theklabel.com"],
    storefront: "UK",
    currency: "GBP",
    note: "Official The K Label London womenswear store; exact label identity, founder/company details, and GBP catalogue verified.",
  },
  {
    id: 1778,
    brandName: "VEIN",
    homepageUrl: "https://www.vein-official.com",
    sources: ["https://www.vein-official.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official VEIN Japanese store; exact label identity, designer Koki Enomoto, collections, and JPY catalogue verified.",
  },
  {
    id: 2149,
    brandName: "0Tape",
    homepageUrl: "https://tape00.cafe24.com",
    sources: ["https://tape00.cafe24.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official 0Tape Korean store; exact brand identity, Seoul business registration, brand contact, and KRW catalogue verified.",
  },
  {
    id: 2158,
    brandName: "Samostuff",
    homepageUrl: "https://samostuff.com",
    sources: ["https://samostuff.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official Samostuff Korean store; exact brand identity, Seoul business details, direct ordering pages, and KRW catalogue verified.",
  },
  {
    id: 2211,
    brandName: "Whateverwewant",
    homepageUrl: "https://whateverwewant.co.kr",
    sources: ["https://whateverwewant.co.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official Whateverwewant Korean store; exact brand identity, Seoul business details, and KRW catalogue verified.",
  },
  {
    id: 2229,
    brandName: "Yiyae",
    homepageUrl: "https://yiyae.co.kr",
    sources: ["https://yiyae.co.kr", "https://m.yiyae.co.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official YIYAE Korean store; exact brand identity, Seoul stockist/contact information, and direct Korean storefront verified.",
  },
  {
    id: 2232,
    brandName: "The Sugar Punch",
    homepageUrl: "https://sugar-punch.com/en",
    sources: ["https://sugar-punch.com/en", "https://sugar-punch.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official The Sugar Punch Tokyo store; exact brand identity, English/Japanese storefront, worldwide shipping, and JPY catalogue verified.",
  },
  {
    id: 1085,
    brandName: "BONBOM",
    homepageUrl: "https://www.b-o-n-b-o-m.com",
    sources: ["https://www.b-o-n-b-o-m.com", "https://www.ssense.com/en-kr/women/designers/bonbom"],
    storefront: "GLOBAL",
    note: "Official BONBOM brand site; exact label identity and contact/social linkage corroborated with the current designer catalogue.",
  },
  {
    id: 1095,
    brandName: "Shoes Master",
    homepageUrl: "https://www.shoesmaster.jp",
    sources: ["https://www.shoesmaster.jp", "https://www.shoesmaster.jp/about/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official SHOES MASTER magazine site; publisher, editorial contacts, publication history, and current issues verified.",
  },
  {
    id: 1132,
    brandName: "ioannes",
    homepageUrl: "https://ioannes.eu",
    sources: ["https://ioannes.eu", "https://fw24.fashionweek.berlin/en/brands/marke-detail/ioannes.html"],
    storefront: "EU",
    currency: "EUR",
    note: "Official ioannes store; Berlin label identity and brand-domain contact corroborated by Berlin Fashion Week, with regional KRW support available.",
  },
  {
    id: 1139,
    brandName: "Bloke",
    homepageUrl: "https://bloke.world",
    sources: ["https://bloke.world/about/", "https://lagosfashionweek.ng/designers/bloke"],
    storefront: "NG",
    note: "Official BLOKE site; Nigerian founder history, label identity, production practice, and official fashion-week profile verified.",
  },
  {
    id: 1168,
    brandName: "Pristine",
    homepageUrl: "https://www.pristine.land",
    sources: ["https://www.pristine.land/pages/about", "https://www.pristine.land"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Pristine womenswear store; exact London label positioning, designer identity, and GBP catalogue verified.",
  },
  {
    id: 1185,
    brandName: "Seventh",
    homepageUrl: "https://seventhstores.com",
    sources: ["https://seventhstores.com"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Seventh London store; exact contemporary label identity, company/social linkage, and GBP catalogue verified.",
  },
  {
    id: 1224,
    brandName: "Shawna Wu",
    homepageUrl: "https://shawnawu.com",
    sources: ["https://shawnawu.com", "https://shawnawu.com/pages/info"],
    storefront: "US",
    currency: "USD",
    note: "Official Shawna Wu designer store; exact artist identity, collection archive, press credentials, and USD catalogue verified.",
  },
  {
    id: 1226,
    brandName: "The World Is Your Oyster",
    homepageUrl: "https://theworldisyouroyster.net",
    sources: ["https://theworldisyouroyster.net/pages/about-us", "https://theworldisyouroyster.net/collections/all"],
    storefront: "HK",
    note: "Official The World Is Your Oyster store; exact Hong Kong label story, founder identity, collections, and worldwide shipping verified.",
  },
  {
    id: 1241,
    brandName: "YAKU",
    homepageUrl: "https://yaku.uk",
    sources: ["https://yaku.uk/about", "https://shop.yaku.uk"],
    storefront: "UK",
    currency: "GBP",
    note: "Official YAKU site and shop; London founder story, BFC credentials, collections, and GBP direct storefront verified.",
  },
  {
    id: 1278,
    brandName: "OSPERA",
    homepageUrl: "https://ospera.kr",
    sources: ["https://ospera.kr/design/about.html", "https://ospera.kr/product/surface-edition-x-osp%C4%92ra-no013-effector/59/"],
    storefront: "KR",
    currency: "KRW",
    note: "Official OSPERA Korean store; brand story, Seoul business registration, Korean manufacturing, and KRW catalogue verified.",
  },
  {
    id: 1299,
    brandName: "Fax Copy Express",
    homepageUrl: "https://faxcopyexpress.store",
    sources: ["https://faxcopyexpress.store/pages/about-us", "https://faxcopyexpress.store/collections/all"],
    storefront: "CN",
    note: "Official Fax Copy Express store; exact Shanghai label identity, founder story, sustainability positioning, and catalogue verified.",
  },
  {
    id: 1324,
    brandName: "FIDAN NOVRUZOVA",
    homepageUrl: "https://fidannovruzova.com",
    sources: ["https://fidannovruzova.com", "https://fidannovruzova.com/pages/fw26"],
    storefront: "EU",
    currency: "EUR",
    note: "Official FIDAN NOVRUZOVA store; exact designer identity, collection archive, company pages, and EUR catalogue verified.",
  },
  {
    id: 1327,
    brandName: "SELASI",
    homepageUrl: "https://selasi.co",
    sources: ["https://selasi.co/pages/info", "https://londonfashionweek.co.uk/designers/selasi"],
    storefront: "UK",
    note: "Official SELASI site; brand-domain contact and London founder history corroborated by the official London Fashion Week profile.",
  },
  {
    id: 1335,
    brandName: "JiyongKim",
    homepageUrl: "https://www.jiyongkim.net",
    sources: ["https://www.jiyongkim.net"],
    storefront: "KR",
    currency: "KRW",
    note: "Official JiyongKim Korean store; Korean company registration, Seoul contact, KR/international region selector, and direct catalogue verified.",
  },
  {
    id: 1476,
    brandName: "Her Children",
    homepageUrl: "https://her-children.com",
    sources: ["https://her-children.com", "https://www.vogue.com/brands/herchildren"],
    storefront: "GLOBAL",
    note: "Official Her Children storefront; exact label identity, current collection/shop, and designer profile corroborated.",
  },
  {
    id: 85,
    brandName: "SIRE",
    homepageUrl: "https://sire.paris",
    sources: ["https://sire.paris/about/", "https://sire.paris/shop/"],
    storefront: "EU",
    currency: "EUR",
    note: "Official SIRE menswear site; founder history, Paris/Tokyo production identity, brand contact, and shop verified.",
  },
  {
    id: 809,
    brandName: "Teak",
    homepageUrl: "https://teak.co.kr",
    sources: ["https://teak.co.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official TEAK Korean storefront; exact label identity, brand contact, Korean checkout, and KRW catalogue verified.",
  },
  {
    id: 822,
    brandName: "YOUTHBATH",
    homepageUrl: "https://www.youthbath.com",
    sources: ["https://www.youthbath.com/product/list.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official YOUTH BATH Korean store; Korean company registration, Seoul contact, collections, and KRW checkout verified.",
  },
  {
    id: 830,
    brandName: "aeae",
    homepageUrl: "https://ae-ae.kr",
    sources: ["https://ae-ae.kr/product/list.html?cate_no=52", "https://ae-ae.kr/member/agreement.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official aeae Korean store; brand-operated mall, Korean business registration, official-channel linkage, and KRW catalogue verified.",
  },
  {
    id: 838,
    brandName: "NACHE",
    homepageUrl: "https://nache.kr",
    sources: ["https://nache.kr", "https://en.nache.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official NACHE Korean store; Seoul business details, exact label identity, worldwide selector, and KRW catalogue verified.",
  },
  {
    id: 860,
    brandName: "Kusneuf",
    homepageUrl: "https://www.kusneuf.com",
    sources: ["https://www.kusneuf.com/home", "https://us.kusneuf.com/about_"],
    storefront: "KR",
    currency: "KRW",
    note: "Official KUSNEUF Korean store; founder story, Korean business registration/contact, global shop, and catalogue verified.",
  },
  {
    id: 881,
    brandName: "XXXXXXSOCIETY",
    homepageUrl: "https://xxxxxxsociety.com",
    sources: ["https://xxxxxxsociety.com", "https://xxxxxxsociety.com/690561316/?idx=338"],
    storefront: "KR",
    currency: "USD",
    note: "Official XXXXXXSOCIETY store; exact manufacturer and brand fields, South Korean origin, and worldwide-shipping catalogue verified.",
  },
  {
    id: 897,
    brandName: "YOUTH IN BALACLAVA",
    homepageUrl: "https://www.youthsinbalaclava.com",
    sources: ["https://www.youthsinbalaclava.com", "https://www.youthsinbalaclava.com/en-us/pages/contact-us"],
    storefront: "SG",
    currency: "SGD",
    note: "Official Youths In Balaclava store; exact Singapore collective identity, domain contact, collections, and SGD catalogue verified.",
  },
  {
    id: 910,
    brandName: "1XBLUE",
    homepageUrl: "https://1xblue.com",
    sources: ["https://1xblue.com", "https://1xblue.com/collections/all"],
    storefront: "UK",
    currency: "GBP",
    note: "Official 1XBLUE London store; exact label identity, official company linkage, lookbooks, and GBP catalogue verified.",
  },
  {
    id: 925,
    brandName: "1CONCEPT",
    homepageUrl: "https://www.1concept.world",
    sources: ["https://www.1concept.world"],
    storefront: "EU",
    currency: "EUR",
    note: "Official 1CONCEPT fashion and jewelry site; exact company identity and official website corroborated by its company profile.",
  },
  {
    id: 959,
    brandName: "softandwet",
    homepageUrl: "https://www.softandwetundies.com",
    sources: ["https://www.softandwetundies.com/pages/about", "https://www.softandwetundies.com/policies/privacy-policy"],
    storefront: "EU",
    currency: "EUR",
    note: "Official softandwet site; Italian founder story, exact social/contact identity, and store policies verified; shop currently closed.",
  },
  {
    id: 990,
    brandName: "Amy Crookes",
    homepageUrl: "https://www.amycrookes.com",
    sources: ["https://www.amycrookes.com", "https://www.amycrookes.com/collection"],
    storefront: "GLOBAL",
    note: "Official Amy Crookes designer site; exact name, footwear and ready-to-wear collection, contact, and policies verified.",
  },
  {
    id: 1056,
    brandName: "Kathryn Bowen",
    homepageUrl: "https://kathrynbowen.com",
    sources: ["https://kathrynbowen.com/pages/contact", "https://kathrynbowen.com/pages/customer-care"],
    storefront: "CA",
    currency: "CAD",
    note: "Official Kathryn Bowen store; Toronto studio address, brand-domain contacts, direct orders, and Canadian shipping verified.",
  },
  {
    id: 1063,
    brandName: "August Barron",
    homepageUrl: "https://augustbarron.com",
    sources: ["https://augustbarron.com", "https://www.lvmhprize.com/en/august-barron"],
    storefront: "EU",
    currency: "EUR",
    note: "Official August Barron store; 2025 rebrand from ALL-IN, founder identity, LVMH Prize profile, and EUR catalogue verified.",
  },
  {
    id: 1077,
    brandName: "SUBSURFACE",
    homepageUrl: "https://subsurface.tv",
    sources: ["https://subsurface.tv", "https://subsurface.tv/pages/about-us"],
    storefront: "US",
    currency: "USD",
    note: "Official SUBSURFACE store; Los Angeles founder story, exact label identity, brand-domain contacts, and USD catalogue verified.",
  },
  {
    id: 340,
    brandName: "Wind Vintage",
    homepageUrl: "https://www.windvintage.com",
    sources: ["https://www.windvintage.com/about", "https://www.windvintage.com/contact"],
    storefront: "US",
    currency: "USD",
    note: "Official Wind Vintage dealer site; founder, Palm Beach contact, watch inventory, and advisory business verified.",
  },
  {
    id: 448,
    brandName: "WIENERBLUT",
    homepageUrl: "https://wienerblut.at/en/",
    sources: ["https://wienerblut.at/en/", "https://wienerblut.at/en/pages/terms/"],
    storefront: "EU",
    currency: "EUR",
    note: "Official WienerBlut fragrance store; Vienna company identity, brand terms, products, and EUR storefront verified.",
  },
  {
    id: 493,
    brandName: "Caes",
    homepageUrl: "https://www.caes-store.com",
    sources: ["https://www.caes-store.com/pages/our-story", "https://www.caes-store.com/collections/all"],
    storefront: "EU",
    currency: "EUR",
    note: "Official CAES store; Dutch founder story, exact label identity, collections, and EUR catalogue verified.",
  },
  {
    id: 515,
    brandName: "Factor's",
    homepageUrl: "https://www.f-act-ors.com",
    sources: ["https://www.f-act-ors.com", "https://www.f-act-ors.com/shop"],
    storefront: "US",
    currency: "USD",
    note: "Official Factor's storefront; exact stylized label identity and USD apparel catalogue verified.",
  },
  {
    id: 543,
    brandName: "Wed",
    homepageUrl: "https://www.wed-studio.com",
    sources: ["https://www.wed-studio.com/pages/about", "https://www.wed-studio.com/collections/all"],
    storefront: "UK",
    currency: "GBP",
    note: "Official WED Studio site; Central Saint Martins founder history, London bridal label identity, and collections verified.",
  },
  {
    id: 584,
    brandName: "Still Kelly",
    homepageUrl: "https://stillkelly.com",
    sources: ["https://stillkelly.com", "https://stillkelly.com/collections/all"],
    storefront: "US",
    currency: "USD",
    note: "Official Still Kelly store; exact label identity, linked social/contact pages, and USD catalogue verified.",
  },
  {
    id: 694,
    brandName: "Diaper Book Club",
    homepageUrl: "https://diaperbookclub.com",
    sources: ["https://diaperbookclub.com/pages/about", "https://diaperbookclub.com/collections/all"],
    storefront: "US",
    currency: "USD",
    note: "Official Diaper Book Club storefront; exact creator story and USD books, clothing, and accessories catalogue verified.",
  },
  {
    id: 748,
    brandName: "Rush Hour",
    homepageUrl: "https://www.rushhour.nl",
    sources: ["https://www.rushhour.nl/contact", "https://www.rushhour.nl/shipping-support"],
    storefront: "EU",
    currency: "EUR",
    note: "Official Rush Hour Amsterdam record-store and label site; company address, VAT details, mail-order shop, and worldwide shipping verified.",
  },
  {
    id: 792,
    brandName: "Nowos",
    homepageUrl: "https://tee-nowos.com",
    sources: ["https://nowos.jp", "https://tee-nowos.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official NOWOS brand and head-shop storefront; exact label identity, Tokyo address, collections, and JPY shop verified.",
  },
  {
    id: 4988,
    brandName: "BENJAMIN BENMOYAL",
    homepageUrl: "https://benmoyal.com",
    sources: ["https://benmoyal.com/pages/about-us", "https://benmoyal.com/collections/all"],
    storefront: "EU",
    currency: "EUR",
    note: "Official BENMOYAL store; the brand's about page documents its 2025 name change from Benjamin Benmoyal, and the EUR catalogue confirms the same label.",
  },
  {
    id: 5731,
    brandName: "Jirene Studio",
    homepageUrl: "https://jirenestudio.com",
    sources: ["https://jirenestudio.com", "https://jirenestudio.com/pages/contact"],
    storefront: "VN",
    currency: "VND",
    note: "Official Jirene Studio storefront; exact brand identity, Vietnam contact details, retail locations, and VND catalogue verified.",
  },
  {
    id: 5735,
    brandName: "MONICO",
    homepageUrl: "https://monicomode.com",
    sources: ["https://monicomode.com", "https://monicomode.com/pages/contact"],
    storefront: "VN",
    currency: "VND",
    note: "Official MONICO storefront; exact MONICO MODE identity, Vietnam contact details, social linkage, and VND catalogue verified.",
  },
  {
    id: 4952,
    brandName: "AKIRANAKA",
    homepageUrl: "https://akiranaka.com",
    sources: ["https://akiranaka.com/005-4/", "https://store.akiranaka.com"],
    storefront: "JP",
    currency: "JPY",
    note: "Official AKIRANAKA site; official-store linkage, collections, stockists, and Japanese online-store operation verified.",
  },
  {
    id: 4957,
    brandName: "CHIKA KISADA",
    homepageUrl: "https://www.chikakisada.com",
    sources: ["https://www.chikakisada.com"],
    storefront: "JP",
    note: "Official CHIKA KISADA brand site; exact name and matching @chikakisada identity corroborated by industry brand profiles.",
  },
  {
    id: 4959,
    brandName: "TANAKA DAISUKE",
    homepageUrl: "https://tanakadaisuke.jp",
    sources: ["https://tanakadaisuke.jp", "https://tanakadaisuke.jp/collections"],
    storefront: "JP",
    currency: "JPY",
    note: "Official tanakadaisuke Japanese store; exact matching social identity, official-store label, and JPY products verified.",
  },
  {
    id: 4960,
    brandName: "COGNOMEN",
    homepageUrl: "https://cognomen.jp",
    sources: ["https://cognomen.jp", "https://shop.cognomen.jp/pages/home"],
    storefront: "JP",
    currency: "JPY",
    note: "Official COGNOMEN site; matching social identity, concept, collections, official shop link, and JPY catalogue verified.",
  },
  {
    id: 4968,
    brandName: "HANKIM",
    homepageUrl: "https://hankim.co.uk",
    sources: ["https://hankim.co.uk", "https://hankim.co.uk/contact.html"],
    storefront: "UK",
    currency: "GBP",
    note: "Official HANKIM site; exact matching @mynameishankim identity, collections, shop, and domain contacts verified.",
  },
  {
    id: 4972,
    brandName: "IZZY DU",
    homepageUrl: "https://izzydu.co",
    sources: ["https://izzydu.co/pages/about", "https://izzydu.co/collections"],
    storefront: "UK",
    currency: "GBP",
    note: "Official IZZY DU store; designer history, London studio contacts, collections, and GBP products verified.",
  },
  {
    id: 4974,
    brandName: "RXQUETTE",
    homepageUrl: "https://rxquette.co",
    sources: ["https://rxquette.co"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official RXQUETTE store; exact matching social identity, about, collections, boutique, and international region selector verified.",
  },
  {
    id: 1592,
    brandName: "Atu Body Couture",
    homepageUrl: "https://atubodycouture.ro",
    sources: ["https://atubodycouture.ro/pages/about", "https://atubodycouture.ro/collections/shop"],
    storefront: "EU",
    currency: "EUR",
    note: "Official ATU Body Couture store; Romanian brand history, Bucharest contact, international shipping, and EUR catalogue verified.",
  },
  {
    id: 1707,
    brandName: "ANDREJ GRONAU",
    homepageUrl: "https://www.andrejgronau.com",
    sources: ["https://www.andrejgronau.com", "https://www.andrejgronau.com/contact.html"],
    storefront: "EU",
    currency: "EUR",
    note: "Official eponymous label site; exact matching social handle, brand collections, and domain-based studio contacts verified.",
  },
  {
    id: 1765,
    brandName: "Stanley Raffington",
    homepageUrl: "https://www.stanleyraffington.com",
    sources: ["https://www.stanleyraffington.com", "https://www.stanleyraffington.com/blank"],
    storefront: "UK",
    currency: "GBP",
    note: "Official eponymous studio site; exact matching social handle and domain-based studio contact verified.",
  },
  {
    id: 1782,
    brandName: "Idea Book",
    homepageUrl: "https://www.ideanow.online",
    sources: ["https://www.ideanow.online", "https://www.ideanow.online/hard-corps"],
    storefront: "UK",
    currency: "GBP",
    note: "Official IDEA publishing/store site; matching @idea.ltd identity, London store listing, and branded editorial/shop content verified.",
  },
  {
    id: 1794,
    brandName: "Tondolo",
    homepageUrl: "https://www.tondolo.co.uk",
    sources: ["https://www.tondolo.co.uk", "https://www.tondolo.co.uk/collections"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Tondolo store; exact brand identity, matching official social identity, domain contact, and GBP catalogue verified.",
  },
  {
    id: 1811,
    brandName: "Kamushki",
    homepageUrl: "https://kamushki.studio",
    sources: ["https://kamushki.studio/collections"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official Kamushki Jewellery site; exact matching social identity, founders, brand story, and collections verified.",
  },
  {
    id: 1816,
    brandName: "Vanina",
    homepageUrl: "https://vanina.me",
    sources: ["https://vanina.me", "https://vanina.me/pages/story-page"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official Lebanese Vanina store; historical vaninaworld identity, Beirut founders and flagship, and USD catalogue verified.",
  },
  {
    id: 1985,
    brandName: "CIRIACO",
    homepageUrl: "https://madebyciriaco.us",
    sources: ["https://madebyciriaco.us", "https://madebyciriaco.us/collections/all"],
    storefront: "US",
    currency: "USD",
    note: "Official CIRIACO store; exact madebyciriaco identity and USD branded handbag catalogue verified.",
  },
  {
    id: 1994,
    brandName: "Local European",
    homepageUrl: "https://localeuropean.com",
    sources: ["https://localeuropean.com", "https://localeuropean.com/en-se/pages/home"],
    storefront: "US",
    currency: "USD",
    note: "Official LOCAL EUROPEAN store; exact matching social identity, company pages, and USD catalogue verified.",
  },
  {
    id: 2040,
    brandName: "Netta",
    homepageUrl: "https://shopnetta.com",
    sources: ["https://shopnetta.com/pages/about", "https://shopnetta.com/ready-to-wear"],
    storefront: "US",
    currency: "USD",
    note: "Official Netta label store; ethical-brand about page and USD ready-to-wear catalogue verified.",
  },
  {
    id: 2436,
    brandName: "Lucy Delius Jewellery",
    homepageUrl: "https://lucydelius.com",
    sources: ["https://lucydelius.com"],
    storefront: "UK",
    currency: "GBP",
    note: "Official eponymous jewellery store; matching social identity, London shop, domain contacts, and product collections verified.",
  },
  {
    id: 2476,
    brandName: "TENDER PERSON",
    homepageUrl: "https://tenderperson.com",
    sources: ["https://tenderperson.com/pages/about", "https://tenderperson.com/collections"],
    storefront: "JP",
    currency: "JPY",
    note: "Official TENDER PERSON Japanese store; brand history, official-online-store label, and JPY products verified.",
  },
  {
    id: 2482,
    brandName: "NADA Not NADA",
    homepageUrl: "https://nada-rebirth.stores.jp",
    sources: ["https://nada-rebirth.stores.jp", "https://nada-rebirth.com/about/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official NADA. Japanese store; matching nada_not_nada social identity, brand-site linkage, and JPY catalogue verified.",
  },
  {
    id: 2484,
    brandName: "H.UNIT",
    homepageUrl: "https://hunit.shop-pro.jp",
    sources: ["https://hunit.shop-pro.jp"],
    storefront: "JP",
    currency: "JPY",
    note: "Official H.UNIT online shop; brand concept, direct-store statement, company news, and JPY products verified.",
  },
  {
    id: 3806,
    brandName: "UNLIKELY",
    homepageUrl: "https://unlikely.jp",
    sources: ["https://unlikely.jp", "https://unlikely.jp/pages/about-our-brand"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Unlikely Japanese shop; Tokyo founding story, exact brand identity, collections, and JPY products verified.",
  },
  {
    id: 3809,
    brandName: "GIM CONTEXT",
    homepageUrl: "https://gimcontext.com",
    sources: ["https://gimcontext.com", "https://gimcontext.com/pages/about"],
    storefront: "JP",
    currency: "JPY",
    note: "Official gim context Japanese store; exact brand, about page, bilingual site, and JPY catalogue verified.",
  },
  {
    id: 2700,
    brandName: "PAES",
    homepageUrl: "https://p-aes.com",
    sources: ["https://p-aes.com", "https://p-aes.com/legal.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official PAES Korean shop; official-mall exclusives, Korea selector, Seoul business registration, and won prices verified.",
  },
  {
    id: 3871,
    brandName: "WEBHOUSE",
    homepageUrl: "https://webhouse.live",
    sources: ["https://webhouse.live"],
    storefront: "KR",
    currency: "KRW",
    note: "Official WEBHOUSE brand site; exact brand and matching social identity verified.",
  },
  {
    id: 3872,
    brandName: "GYULMEDAL",
    homepageUrl: "https://www.gyulmedal.com",
    sources: ["https://www.gyulmedal.com", "https://www.gyulmedal.com/OURSTORY"],
    storefront: "KR",
    currency: "KRW",
    note: "Official Korean GYULMEDAL shop; matching social identity, Jeju business registration, and won products verified.",
  },
  {
    id: 3874,
    brandName: "TANSANMAGNESIUM",
    homepageUrl: "https://tansanmagnesium.kr",
    sources: ["https://tansanmagnesium.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official Korean TANSANMAGNESIUM shop; exact domain and social identity, Korean business registration, and domestic shop verified.",
  },
  {
    id: 3877,
    brandName: "CONICHIWA bonjour",
    homepageUrl: "https://conichiwabonjour.com",
    sources: ["https://conichiwabonjour.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official CONICHIWA bonjour Korean shop; exact brand identity and KRW catalogue verified.",
  },
  {
    id: 3882,
    brandName: "MASCOMPANY",
    homepageUrl: "https://www.mascompany.kr",
    sources: ["https://www.mascompany.kr"],
    storefront: "KR",
    currency: "KRW",
    note: "Official MASCOMPANY Korean shop; exact brand identity, Seoul business registration, and matching brand contact verified.",
  },
  {
    id: 3886,
    brandName: "TYPESERVICE",
    homepageUrl: "https://typeserviceweb.com",
    sources: ["https://typeserviceweb.com"],
    storefront: "KR",
    currency: "KRW",
    note: "Official TYPESERVICE shop; TYPE SERVICE WEB identity and TYPESERVICE CO., LTD. operator verified.",
  },
  {
    id: 3888,
    brandName: "URAGO",
    homepageUrl: "https://u-rago.com",
    sources: ["https://u-rago.com/SHOP", "https://u-rago.com/826?mode=privacy"],
    storefront: "KR",
    currency: "KRW",
    note: "Official URAGO Korean shop; exact brand, Seoul business registration, and won catalogue verified.",
  },
  {
    id: 3891,
    brandName: "BOHEMSEO",
    homepageUrl: "https://bohemseo.com",
    sources: ["https://bohemseo.com", "https://bohemseo.com/article/notice/1/4390/"],
    storefront: "KR",
    currency: "KRW",
    note: "Official BOHEMSEO Korean shop; matching bohemian_seoul identity and brand-operated Seoul store notice verified.",
  },
  {
    id: 3895,
    brandName: "POSZER",
    homepageUrl: "https://poszer.com",
    sources: ["https://poszer.com", "https://poszer.com/shopinfo/contact.html"],
    storefront: "KR",
    currency: "KRW",
    note: "Official POSZER Korean shop; matching social handle, Seoul company registration, contact, and collection pages verified.",
  },
  {
    id: 1069,
    brandName: "B1ARCHIVE",
    homepageUrl: "https://b1archivee.com",
    sources: ["https://b1archivee.com"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official B1ARCHIVE shop; exact brand identity, matching official social identity, and USD products verified.",
  },
  {
    id: 1201,
    brandName: "STRONGTHE",
    homepageUrl: "https://www.strongthe.com",
    sources: ["https://www.strongthe.com"],
    storefront: "UK",
    currency: "GBP",
    note: "Official STRONGTHE shop; exact brand identity and GBP product catalogue verified.",
  },
  {
    id: 1210,
    brandName: "Sherris",
    homepageUrl: "https://sherris.shop",
    sources: ["https://sherris.shop"],
    storefront: "US",
    currency: "USD",
    note: "Official Sherris shop; exact brand identity, New York production statement, and USD products verified.",
  },
  {
    id: 1230,
    brandName: "Sultry Virgin",
    homepageUrl: "https://sultryvirgin.com",
    sources: ["https://sultryvirgin.com", "https://sultryvirgin.com/pages/about-us"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official Sultry Virgin shop; exact brand identity, brand about page, and USD product catalogue verified.",
  },
  {
    id: 1357,
    brandName: "A BETTER FEELING",
    homepageUrl: "https://www.abetterfeeling.com",
    sources: ["https://www.abetterfeeling.com", "https://www.abetterfeeling.com/pages/about"],
    storefront: "UK",
    currency: "GBP",
    note: "Official A BETTER FEELING shop; exact brand identity and London brand history verified.",
  },
  {
    id: 1403,
    brandName: "RICE NINE TEN",
    homepageUrl: "https://ricenineten.com",
    sources: ["https://ricenineten.com", "https://ricenineten.biz"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Japanese RICE NINE TEN e-store; exact brand identity, official brand-site linkage, and JPY checkout verified.",
  },
  {
    id: 1407,
    brandName: "Mordecai",
    homepageUrl: "https://www.mordecaistudio.com",
    sources: ["https://www.mordecaistudio.com", "https://www.mordecaistudio.com/about"],
    storefront: "IT",
    currency: "EUR",
    note: "Official Italian Mordecai label site; exact brand identity, founder history, collections, stores, and brand social link verified.",
  },
  {
    id: 1430,
    brandName: "The Ouze",
    homepageUrl: "https://the-ouze.com",
    sources: ["https://the-ouze.com/pages/about-us", "https://the-ouze.com/pages/contact"],
    storefront: "UK",
    currency: "GBP",
    note: "Official The Ouze jewellery shop; founder history, brand contact addresses, and British storefront verified.",
  },
  {
    id: 1432,
    brandName: "Unbranded",
    homepageUrl: "https://theunbrandedbrand.com",
    sources: ["https://theunbrandedbrand.com", "https://theunbrandedbrand.com/pages/about-us"],
    storefront: "CA",
    currency: "USD",
    note: "Official The Unbranded Brand shop; DB social handle, Canadian brand identity, about page, and product catalogue verified.",
  },
  {
    id: 1474,
    brandName: "Big Bell Ceramics",
    homepageUrl: "https://www.bigbellceramics.com",
    sources: ["https://www.bigbellceramics.com", "https://www.bigbellceramics.com/about"],
    storefront: "US",
    currency: "USD",
    note: "Official Big Bell Ceramics shop; exact brand and matching social identity, shop, about, and contact sections verified.",
  },
  {
    id: 1504,
    brandName: "Maison La Plage",
    homepageUrl: "https://maisonlaplage.com",
    sources: ["https://maisonlaplage.com", "https://maisonlaplage.com/en/about-us/"],
    storefront: "TR",
    currency: "TRY",
    note: "Official Turkish Maison La Plage site; exact brand and matching social identity, Istanbul origin, collection, and about page verified.",
  },
  {
    id: 40,
    brandName: "Abelia edoward goucha",
    homepageUrl: "https://abeliaedowardgoucha.com",
    sources: ["https://abeliaedowardgoucha.com", "https://abeliaedowardgoucha.com/collections/all"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Japanese brand shop; exact brand identity and JPY/JA storefront verified.",
  },
  {
    id: 50,
    brandName: "COLLEEN ALLEN",
    homepageUrl: "https://colleenallen.com",
    sources: ["https://colleenallen.com/collections/", "https://colleenallen.com/pages/about"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official eponymous brand store; brand identity, contact domain, and USD products verified.",
  },
  {
    id: 96,
    brandName: "Nuba",
    homepageUrl: "https://www.nuba.world",
    sources: ["https://www.nuba.world/shop"],
    storefront: "UK",
    currency: "GBP",
    note: "Official Nuba studio shop; London label identity corroborated by its shop and stockist coverage.",
  },
  {
    id: 98,
    brandName: "TMS.SITE",
    homepageUrl: "https://www.tms.site",
    sources: ["https://www.tms.site/pages/stockists"],
    storefront: "HK",
    currency: "HKD",
    note: "Official TMS.SITE shop; exact brand identity and Hong Kong business contact verified.",
  },
  {
    id: 101,
    brandName: "Gabe Gordon",
    homepageUrl: "https://gabe-gordon.com",
    sources: ["https://gabe-gordon.com", "https://gabe-gordon.com/info/about"],
    storefront: "GLOBAL",
    currency: "USD",
    note: "Official eponymous New York brand store; identity, about page, and USD products verified.",
  },
  {
    id: 124,
    brandName: "OUAT",
    homepageUrl: "https://www.ou-at.com",
    sources: ["https://www.ou-at.com/about"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Japanese OUAT shop; exact brand identity and official commerce/legal pages verified.",
  },
  {
    id: 154,
    brandName: "Oct31",
    homepageUrl: "https://oct31.kr",
    sources: ["https://oct31.kr", "https://m.oct31.kr/member/login.html"],
    note: "Official Korean Cafe24 shop; Oct31 identity and Korean business registration verified.",
  },
  {
    id: 160,
    brandName: "SEEKINGS",
    homepageUrl: "https://seekings.co",
    sources: ["https://seekings.co"],
    storefront: "US",
    currency: "USD",
    note: "Official SEEKINGS shop; exact brand identity, Los Angeles contact, and USD checkout verified.",
  },
  {
    id: 320,
    brandName: "SSIL",
    homepageUrl: "https://s-sil.com",
    sources: ["https://s-sil.com/product/list.html", "https://en.s-sil.com"],
    note: "Official Korean storefront explicitly labels KR/KRW and links its EN/USD counterpart.",
  },
  {
    id: 495,
    brandName: "INSILENCE WOMEN",
    homepageUrl: "https://insilence.co.kr",
    sources: ["https://insilence.co.kr", "https://insilence.co.kr/board/notice/1/"],
    note: "Official INSILENCE Korean shop includes a dedicated women category and Korean storefront selector.",
  },
  {
    id: 545,
    brandName: "COMME SE-A",
    homepageUrl: "https://commesea.com",
    sources: ["https://commesea.com", "https://en.commesea.com"],
    note: "Official Korean storefront; KR selector, brand identity, and Seoul business registration verified.",
  },
  {
    id: 827,
    brandName: "산산기어",
    homepageUrl: "https://sansangear.com",
    sources: ["https://sansangear.com", "https://sansangear.com/pages/info"],
    note: "Official Korean storefront; site declares market KR, language ko, and KRW checkout.",
  },
  {
    id: 1131,
    brandName: "Epingler",
    homepageUrl: "https://epingler.com",
    sources: ["https://epingler.com", "https://epingler.com/about"],
    note: "Official Korean brand shop; Instagram identity, Seoul address, and KRW product prices verified.",
  },
  {
    id: 1439,
    brandName: "Trunk Project",
    homepageUrl: "https://trunk-project.com",
    sources: ["https://trunk-project.com", "https://en.trunk-project.com"],
    note: "Official Korean storefront; KOR/ENG selector and Korean business registration verified.",
  },
  {
    id: 1501,
    brandName: "young n sang",
    homepageUrl: "https://youngnsang.com",
    sources: ["https://youngnsang.com/product/list.html", "https://youngnsang.com/member/agreement.html"],
    note: "Official brand-operated Korean online shop and Korean e-commerce registration verified.",
  },
  {
    id: 1711,
    brandName: "SURGERY",
    homepageUrl: "https://www.sur8ery.com",
    sources: ["https://www.sur8ery.com", "https://www.sur8ery.com/shop"],
    note: "Official Korean brand shop; SURGERY identity, Korean shopping UI, and Seoul business registration verified.",
  },
  {
    id: 1741,
    brandName: "UMARMUNG",
    homepageUrl: "https://umarmung.kr",
    sources: ["https://umarmung.kr/index.html"],
    note: "Official Korean shop; brand identity, Seoul atelier, business registration, and KRW prices verified.",
  },
  {
    id: 192,
    brandName: "CPLUS Series",
    homepageUrl: "https://cplus-series.com",
    sources: ["https://cplus-series.com/campaign.html"],
    storefront: "GLOBAL",
    note: "Official C+plus SERIES brand site; collection, stockist, press, contact, and about sections verified.",
  },
  {
    id: 231,
    brandName: "NICOLAS ANDREAS TARALIS",
    homepageUrl: "https://shop.nicolasandreastaralis.com",
    sources: ["https://shop.nicolasandreastaralis.com", "https://shop.nicolasandreastaralis.com/pages/cdg"],
    storefront: "EU",
    currency: "EUR",
    note: "Official eponymous brand store; legal operator, brand identity, shop, and EUR checkout verified.",
  },
  {
    id: 246,
    brandName: "73 LONDON",
    homepageUrl: "https://73london.com",
    sources: ["https://73london.com/en-us", "https://73london.com/pages/test-about-us"],
    storefront: "UK",
    currency: "GBP",
    note: "Official British label shop; exact 73LONDON identity, about page, and GBP products verified.",
  },
  {
    id: 283,
    brandName: "SAPIO",
    homepageUrl: "https://sapio.website",
    sources: ["https://sapio.website", "https://www.cameramoda.it"],
    storefront: "IT",
    currency: "EUR",
    note: "Official SAPIO collection site; domain corroborated by Camera Nazionale della Moda Italiana materials.",
  },
  {
    id: 303,
    brandName: "NUÉ",
    homepageUrl: "https://www.nue-studio.com",
    sources: ["https://www.nue-studio.com"],
    storefront: "GLOBAL",
    note: "Official NUÉ online store; exact accented brand identity and official-store presentation verified.",
  },
  {
    id: 323,
    brandName: "YLÈVE",
    homepageUrl: "https://www.yleve.jp",
    sources: ["https://www.yleve.jp", "https://www.yleve.jp/shop.html"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Japanese YLÈVE site; exact brand identity, online shop, and Japanese stores verified.",
  },
  {
    id: 332,
    brandName: "OK",
    homepageUrl: "https://okinfo.stores.jp",
    sources: ["https://okinfo.stores.jp"],
    storefront: "JP",
    currency: "JPY",
    note: "Official O.K. Japanese web shop; brand catalog, official notices, and JPY products verified.",
  },
  {
    id: 364,
    brandName: "The Letters",
    homepageUrl: "https://the-letters.net",
    sources: ["https://the-letters.net/pages/store"],
    storefront: "JP",
    currency: "JPY",
    note: "Official The Letters site; exact brand identity and Tokyo flagship store verified.",
  },
  {
    id: 377,
    brandName: "Aurembiaix",
    homepageUrl: "https://www.aurembiaix.com",
    sources: ["https://www.aurembiaix.com/category/all-products", "https://www.aurembiaix.com/info-1"],
    storefront: "EU",
    currency: "EUR",
    note: "Official eponymous shop; exact brand identity, store policy, and EUR products verified.",
  },
  {
    id: 381,
    brandName: "Raga Malak",
    homepageUrl: "https://www.ragamalak.com",
    sources: ["https://www.ragamalak.com/collections", "https://www.ragamalak.com/blogs/news"],
    storefront: "AU",
    note: "Official RAGA MALAK shop; exact brand identity, collections, and brand-owned news section verified.",
  },
  {
    id: 402,
    brandName: "Toraichi",
    homepageUrl: "https://store.toraichi.com",
    sources: ["https://store.toraichi.com", "https://www.corporation.toraichi.com/eng/company/"],
    storefront: "JP",
    currency: "JPY",
    note: "Official Toraichi online store, corroborated by the manufacturer's corporate site.",
  },
  {
    id: 1776,
    brandName: "Leere Intention",
    homepageUrl: "https://leereintention.com",
    sources: ["https://leereintention.com", "https://en.leereintention.com/information"],
    note: "Official Korean storefront; KR selector, Seoul business registration, and won-denominated products verified.",
  },
  {
    id: 2230,
    brandName: "Haveoffduty",
    homepageUrl: "https://haveoffduty.com",
    sources: ["https://haveoffduty.com"],
    note: "Official Korean brand shop; brand identity, Seoul business registration, and KRW prices verified.",
  },
  {
    id: 2552,
    brandName: "IUGAMAKARAS",
    homepageUrl: "https://iugamakaras.com",
    sources: ["https://iugamakaras.com"],
    note: "Official Korean storefront; flagship address, business registration, and KRW prices verified.",
  },
  {
    id: 3830,
    brandName: "Jichoi",
    homepageUrl: "https://jichoi.net",
    sources: ["https://jichoi.net", "https://jichoi.net/product/list.html?cate_no=26"],
    note: "Official Korean storefront; KR selector, JICHOI company identity, and KRW product prices verified.",
  },
  {
    id: 3847,
    brandName: "THOMASMORE",
    homepageUrl: "https://thomasmore.co.kr",
    sources: ["https://thomasmore.co.kr", "https://en.thomasmore.co.kr"],
    note: "Official Korean store; brand identity, Korean business registration, and KRW prices verified.",
  },
  {
    id: 3853,
    brandName: "ESPIONAGE",
    homepageUrl: "https://espionage.co.kr",
    sources: ["https://espionage.co.kr", "https://espionage.co.kr/m/"],
    note: "Official Korean store; ESPIONAGE identity, Seoul business registration, and KRW prices verified.",
  },
] as const

const apply = process.argv.includes("--apply")
const dbUrl = process.env.DB_URL
const dbToken = process.env.DB_TOKEN
if (!dbUrl || !dbToken) throw new Error("DB_URL and DB_TOKEN are required")
const db = createClient(dbUrl, dbToken)

for (const verified of VERIFIED) {
  const {data, error} = await db
    .from("brand_nodes")
    .select("id,brand_name,wiki")
    .eq("id", verified.id)
    .single()
  if (error) throw error
  if (data.brand_name !== verified.brandName) {
    throw new Error(`brand id mismatch: #${verified.id} is ${data.brand_name}, expected ${verified.brandName}`)
  }
  const wiki = data.wiki && typeof data.wiki === "object" ? data.wiki as Record<string, unknown> : {}
  const before = typeof wiki.homepage_url === "string" && wiki.homepage_url.trim() ? wiki.homepage_url.trim() : null
  console.log(`${before ? "SKIP_PRESENT" : apply ? "APPLY" : "DRY_RUN"}\t${verified.id}\t${verified.brandName}\t${verified.homepageUrl}`)
  if (before || !apply) continue
  const {error: updateError} = await db
    .from("brand_nodes")
    .update({wiki: {
      ...wiki,
      homepage_url: verified.homepageUrl,
      homepage_verified_at: new Date().toISOString(),
      homepage_sources: verified.sources,
      homepage_storefront: "storefront" in verified ? verified.storefront : "KR",
      homepage_currency: "currency" in verified ? verified.currency : "KRW",
      homepage_verification_note: verified.note,
    }})
    .eq("id", verified.id)
    .filter("wiki->>homepage_url", "is", null)
  if (updateError) throw updateError
}
